version: 2

jobs:
  test:
    docker:
      - image: circleci/node:stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout
    
      # download and cache dependencies
      - restore_cache:
          keys:
            - v1.1-dependencies-{{ checksum "package.json" }}
            # fallback using latest cache
            - v1.1-dependencies-
        
      - run: npm install
    
      - save_cache:
          paths:
            - node_modules
          key: v1.1-dependencies-{{ checksum "package.json" }}


  deploy:
    docker:
      - image: circleci/node:stretch

    working_directory: ~/repo

    steps:
      - checkout
    
      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback using latest cache
            - v1-dependencies-
        
      - run: npm install
    
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: npm run build

      - add_ssh_keys:
          fingerprints:
            - "fa:04:c7:ee:b3:82:19:0c:a0:18:98:97:1f:5f:8b:a2"
      
      - run: ssh-keyscan 116.203.52.174 >> ~/.ssh/known_hosts
      - run:
          name: copy to server
          command: scp -r build dat18a-hop@116.203.52.174:/var/www/hopfrontend
          
    
workflows:
  version: 2
  node-tests:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
