version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8
    
    working_directory: ~/repo
    
    steps:
      - checkout
    
      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback using latest cache
            - v1-dependencies-
        
      - run: npm install
    
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm test

workflows:
  version: 2
  node-tests:
    jobs:
      - test
